targets:
    distcheck:
        task_args:
            - ./...
    dist-linux-amd64:
        task_args:
            - -ldflags
            - "-X github.com/dwtk/dwtk/internal/version.Version={{.Version}}"
    dist-linux-armv6:
        task_args:
            - -ldflags
            - "-X github.com/dwtk/dwtk/internal/version.Version={{.Version}}"
    dist-linux-armv7:
        task_args:
            - -ldflags
            - "-X github.com/dwtk/dwtk/internal/version.Version={{.Version}}"
